package org.aswing.ext;

extern class GridList extends org.aswing.JViewport, implements org.aswing.event.ListDataListener {
	function new(?model : org.aswing.ListModel, ?cellFactory : GridListCellFactory, ?columns : Int, ?rows : Int) : Void;
	function addSelectionInterval(index0 : Int, index1 : Int, ?programmatic : Bool) : Void;
	function addSelectionListener(listener : Dynamic, ?priority : Int, ?useWeakReference : Bool) : Void;
	function clearSelection(?programmatic : Bool) : Void;
	function contentsChanged(e : org.aswing.event.ListDataEvent) : Void;
	function getAnchorSelectionIndex() : Int;
	function getCellByIndex(index : Int) : GridListCell;
	function getColumns() : Int;
	function getHGap() : Int;
	function getLeadSelectionIndex() : Int;
	function getModel() : org.aswing.ListModel;
	function getRows() : Int;
	function getSelectedIndex() : Int;
	function getSelectedIndices() : Array<Dynamic>;
	function getSelectedValue() : Dynamic;
	function getSelectedValues() : Array<Dynamic>;
	function getSelectionMode() : Int;
	function getSelectionModel() : org.aswing.ListSelectionModel;
	function getTileHeight() : Int;
	function getTileWidth() : Int;
	function getVGap() : Int;
	function intervalAdded(e : org.aswing.event.ListDataEvent) : Void;
	function intervalRemoved(e : org.aswing.event.ListDataEvent) : Void;
	function isAutoScroll() : Bool;
	function isSelectable() : Bool;
	function isSelectedIndex(index : Int) : Bool;
	function isSelectionEmpty() : Bool;
	function removeSelectionInterval(index0 : Int, index1 : Int, ?programmatic : Bool) : Void;
	function scrollToView(value : Dynamic) : Void;
	function scrollToViewIndex(index : Int) : Void;
	function selectAll(?programmatic : Bool) : Void;
	function setAutoScroll(b : Bool) : Void;
	function setColsRows(cols : Int, rows : Int) : Void;
	function setColumns(cols : Int) : Void;
	function setHGap(g : Int) : Void;
	function setHolderLayout(layout : GridListLayout) : Void;
	function setListData(ld : Array<Dynamic>) : Void;
	function setModel(m : org.aswing.ListModel) : Void;
	function setRows(rows : Int) : Void;
	function setSelectable(b : Bool) : Void;
	function setSelectedIndex(index : Int, ?programmatic : Bool) : Void;
	function setSelectedIndices(indices : Array<Dynamic>, ?programmatic : Bool) : Void;
	function setSelectedValue(value : Dynamic, ?programmatic : Bool) : Void;
	function setSelectedValues(values : Array<Dynamic>, ?programmatic : Bool) : Void;
	function setSelectionInterval(index0 : Int, index1 : Int, ?programmatic : Bool) : Void;
	function setSelectionMode(sm : Int) : Void;
	function setSelectionModel(m : org.aswing.ListSelectionModel) : Void;
	function setTileHeight(h : Int) : Void;
	function setTileWidth(w : Int) : Void;
	function setVGap(g : Int) : Void;
	private var autoScroll : Bool;
	private var cellFactory : GridListCellFactory;
	private var cells : org.aswing.util.ArrayList;
	private var gridLayout : GridListLayout;
	private var model : org.aswing.ListModel;
	private var selectable : Bool;
	private var selectionModel : org.aswing.ListSelectionModel;
	private var tileHeight : Int;
	private var tileHolder : GridCellHolder;
	private var tileWidth : Int;
	private function addCellToContainer(cell : GridListCell, index : Int) : Void;
	private function addHandlersToCell(cellCom : org.aswing.Component) : Void;
	private function createHolder(columns : Int, rows : Int) : org.aswing.Container;
	private function createItemEventObj(cellCom : Dynamic, type : String, me : flash.events.MouseEvent) : GridListItemEvent;
	private function createNewCell() : GridListCell;
	private function removeCellFromeContainer(cell : GridListCell) : Void;
	private function removeHandlersFromCell(cellCom : org.aswing.Component) : Void;
	static var MULTIPLE_SELECTION : Int;
	static var SINGLE_SELECTION : Int;
}
