package org.aswing;

extern class AbstractTabbedPane extends Container {
	function new() : Void;
	function addStateListener(listener : Dynamic, ?priority : Int, ?useWeakReference : Bool) : Void;
	function appendTab(com : Component, ?title : String, ?icon : Icon, ?tip : String) : Void;
	function getHorizontalAlignment() : Int;
	function getHorizontalTextPosition() : Int;
	function getIconAt(i : Int) : Icon;
	function getIconTextGap() : Int;
	function getMargin() : Insets;
	function getModel() : SingleSelectionModel;
	function getSelectedComponent() : Component;
	function getSelectedIndex() : Int;
	function getTabCount() : Int;
	function getTipAt(i : Int) : String;
	function getTitleAt(i : Int) : String;
	function getVerticalAlignment() : Int;
	function getVerticalTextPosition() : Int;
	function indexOfIcon(icon : Icon) : Int;
	function indexOfTip(tip : String) : Int;
	function indexOfTitle(title : String) : Int;
	function insertTab(i : Int, com : Component, ?title : String, ?icon : Icon, ?tip : String) : Void;
	function isEnabledAt(index : Int) : Bool;
	function isVisibleAt(index : Int) : Bool;
	function removeStateListener(listener : Dynamic) : Void;
	function removeTabAt(i : Int) : Component;
	function setEnabledAt(index : Int, enabled : Bool) : Void;
	function setHorizontalAlignment(alignment : Int) : Void;
	function setHorizontalTextPosition(textPosition : Int) : Void;
	function setIconAt(i : Int, icon : Icon) : Void;
	function setIconTextGap(iconTextGap : Int) : Void;
	function setMargin(m : Insets) : Void;
	function setModel(model : SingleSelectionModel) : Void;
	function setSelectedComponent(com : Component, ?programmatic : Bool) : Void;
	function setSelectedIndex(i : Int, ?programmatic : Bool) : Void;
	function setTipAt(i : Int, t : String) : Void;
	function setTitleAt(i : Int, t : String) : Void;
	function setVerticalAlignment(alignment : Int) : Void;
	function setVerticalTextPosition(textPosition : Int) : Void;
	function setVisibleAt(index : Int, visible : Bool) : Void;
	private function insertProperties(i : Int, ?title : String, ?icon : Icon, ?tip : String) : Void;
	private function insertToArray(arr : Array<Dynamic>, i : Int, obj : Dynamic) : Void;
	private function removeFromArray(arr : Array<Dynamic>, i : Int) : Void;
	private function removeProperties(i : Int) : Void;
	static var BOTTOM : Int;
	static var CENTER : Int;
	static var HORIZONTAL : Int;
	static var LEFT : Int;
	static var RIGHT : Int;
	static var TOP : Int;
	static var VERTICAL : Int;
}
