package org.aswing;

extern class AssetPane extends Container {
	function new(?asset : flash.display.DisplayObject, ?prefferSizeStrategy : Int) : Void;
	function getActualScale() : Int;
	function getAsset() : flash.display.DisplayObject;
	function getAssetOriginalSize() : org.aswing.geom.IntDimension;
	function getCustomScale() : Int;
	function getHorizontalAlignment() : Float;
	function getOffsetX() : Float;
	function getOffsetY() : Float;
	function getPrefferSizeStrategy() : Float;
	function getScaleMode() : Int;
	function getVerticalAlignment() : Float;
	function isAssetVisible() : Bool;
	function isLoaded() : Bool;
	function isMaskAsset() : Bool;
	function reload() : Void;
	function setAsset(asset : flash.display.DisplayObject) : Void;
	function setAssetVisible(b : Bool) : Void;
	function setCustomScale(scale : Int) : Void;
	function setHorizontalAlignment(?alignment : Int) : Void;
	function setMaskAsset(m : Bool) : Void;
	function setOffsetX(offset : Float) : Void;
	function setOffsetY(offset : Float) : Void;
	function setPrefferSizeStrategy(p : Float) : Void;
	function setScaleMode(mode : Int) : Void;
	function setVerticalAlignment(?alignment : Int) : Void;
	function unloadAsset() : Void;
	private var asset : flash.display.DisplayObject;
	private var assetContainer : flash.display.DisplayObjectContainer;
	private var assetMask : flash.display.Shape;
	private function applyMaskAsset() : Void;
	private function loadFloor() : Void;
	private function resetAsset() : Void;
	private function setAssetOriginalSize(size : org.aswing.geom.IntDimension) : Void;
	private function setLoaded(b : Bool) : Void;
	private function storeOriginalScale() : Void;
	static var BOTTOM : Int;
	static var CENTER : Int;
	static var LEFT : Int;
	static var PREFER_SIZE_BOTH : Int;
	static var PREFER_SIZE_IMAGE : Int;
	static var PREFER_SIZE_LAYOUT : Int;
	static var RIGHT : Int;
	static var SCALE_CUSTOM : Int;
	static var SCALE_FIT_HEIGHT : Int;
	static var SCALE_FIT_PANE : Int;
	static var SCALE_FIT_WIDTH : Int;
	static var SCALE_NONE : Int;
	static var SCALE_STRETCH_PANE : Int;
	static var TOP : Int;
}
