package org.aswing;

extern class Component extends AWSprite {
	function new() : Void;
	function addDragAcceptableInitiator(com : Component) : Void;
	function componentToGlobal(p : org.aswing.geom.IntPoint) : org.aswing.geom.IntPoint;
	function fireDragDropEvent(dragInitiator : Component, sourceData : org.aswing.dnd.SourceData, mousePos : org.aswing.geom.IntPoint) : Void;
	function fireDragEnterEvent(dragInitiator : Component, sourceData : org.aswing.dnd.SourceData, mousePos : org.aswing.geom.IntPoint, relatedTarget : Component) : Void;
	function fireDragExitEvent(dragInitiator : Component, sourceData : org.aswing.dnd.SourceData, mousePos : org.aswing.geom.IntPoint, relatedTarget : Component) : Void;
	function fireDragOverringEvent(dragInitiator : Component, sourceData : org.aswing.dnd.SourceData, mousePos : org.aswing.geom.IntPoint) : Void;
	function getAlignmentX() : Float;
	function getAlignmentY() : Float;
	function getAlpha() : Float;
	function getAwmlID() : String;
	function getAwmlIndex() : Float;
	function getAwmlNamespace() : String;
	function getBackground() : ASColor;
	function getBackgroundDecorator() : GroundDecorator;
	function getBorder() : Border;
	function getClientProperty(key : Dynamic) : Dynamic;
	function getClipBounds() : org.aswing.geom.IntRectangle;
	function getComBounds(?rv : org.aswing.geom.IntRectangle) : org.aswing.geom.IntRectangle;
	function getConstraints() : Dynamic;
	function getDefaultBasicUIClass() : Class<Dynamic>;
	function getFocusManager() : FocusManager;
	function getFont() : ASFont;
	function getForeground() : ASColor;
	function getForegroundDecorator() : GroundDecorator;
	function getGlobalLocation(?rv : org.aswing.geom.IntPoint) : org.aswing.geom.IntPoint;
	function getHeight() : Int;
	function getInsets() : Insets;
	function getInternalFocusObject() : flash.display.InteractiveObject;
	function getKeyboardManager() : KeyboardManager;
	function getLocation(?rv : org.aswing.geom.IntPoint) : org.aswing.geom.IntPoint;
	function getMaximumHeight() : Int;
	function getMaximumSize() : org.aswing.geom.IntDimension;
	function getMaximumWidth() : Int;
	function getMinimumHeight() : Int;
	function getMinimumSize() : org.aswing.geom.IntDimension;
	function getMinimumWidth() : Int;
	function getMousePosition() : org.aswing.geom.IntPoint;
	function getName() : String;
	function getPaintBounds() : org.aswing.geom.IntRectangle;
	function getParent() : Container;
	function getPreferredHeight() : Int;
	function getPreferredSize() : org.aswing.geom.IntDimension;
	function getPreferredWidth() : Int;
	function getRootPaneAncestor() : JRootPane;
	function getSize(?rv : org.aswing.geom.IntDimension) : org.aswing.geom.IntDimension;
	function getToolTipText() : String;
	function getUI() : org.aswing.plaf.ComponentUI;
	function getUIClassID() : String;
	function getWidth() : Int;
	function getX() : Int;
	function getY() : Int;
	function globalToComponent(p : org.aswing.geom.IntPoint) : org.aswing.geom.IntPoint;
	function hitTestMouse() : Bool;
	function invalidate() : Void;
	function invalidatePreferSizeCaches() : Void;
	function isCachePreferSizes() : Bool;
	function isDragAcceptableInitiator(com : Component) : Bool;
	function isDragEnabled() : Bool;
	function isDropTrigger() : Bool;
	function isEnabled() : Bool;
	function isFocusOwner() : Bool;
	function isFocusable() : Bool;
	function isFocusableSet() : Bool;
	function isFontValidated() : Bool;
	function isOnStage() : Bool;
	function isOpaque() : Bool;
	function isOpaqueSet() : Bool;
	function isShowing() : Bool;
	function isUIElement() : Bool;
	function isValid() : Bool;
	function isValidateRoot() : Bool;
	function isVisible() : Bool;
	function makeFocus() : Void;
	function pack() : Void;
	function paintFocusRect(?force : Bool) : Void;
	function paintImmediately() : Void;
	function parentReAppendChildren() : Void;
	function putClientProperty(key : Dynamic, value : Dynamic) : Void;
	function reAppendToParent(?constraints : Dynamic) : Void;
	function removeDragAcceptableInitiator(com : Component) : Void;
	function removeFromContainer() : Void;
	function repaint() : Void;
	function repaintAndRevalidate() : Void;
	function requestFocus() : Bool;
	function revalidate() : Void;
	function revalidateIfNecessary() : Void;
	function setAlignmentX(ax : Float) : Void;
	function setAlignmentY(ay : Float) : Void;
	function setAlpha(alpha : Float) : Void;
	function setAwmlID(id : String) : Void;
	function setAwmlIndex(index : Float) : Void;
	function setAwmlNamespace(theNamespace : String) : Void;
	function setBackground(c : ASColor) : Void;
	function setBackgroundDecorator(bg : GroundDecorator) : Void;
	function setBorder(b : Border) : Void;
	function setBounds(b : org.aswing.geom.IntRectangle) : Void;
	function setCachePreferSizes(b : Bool) : Void;
	function setClipBounds(b : org.aswing.geom.IntRectangle) : Void;
	function setClipSize(size : org.aswing.geom.IntDimension) : Void;
	function setComBounds(b : org.aswing.geom.IntRectangle) : Void;
	function setComBoundsXYWH(x : Int, y : Int, w : Int, h : Int) : Void;
	function setConstraints(constraints : Dynamic) : Void;
	function setDragAcceptableInitiatorAppraiser(func : Dynamic) : Void;
	function setDragEnabled(b : Bool) : Void;
	function setDropTrigger(b : Bool) : Void;
	function setEnabled(b : Bool) : Void;
	function setFocusable(b : Bool) : Void;
	function setFocusableSet(b : Bool) : Void;
	function setFont(newFont : ASFont) : Void;
	function setFontValidated(b : Bool) : Void;
	function setForeground(c : ASColor) : Void;
	function setForegroundDecorator(fg : GroundDecorator) : Void;
	function setGlobalLocation(gp : org.aswing.geom.IntPoint) : Void;
	function setGlobalLocationXY(x : Int, y : Int) : Void;
	function setHeight(height : Float) : Void;
	function setLocation(newPos : org.aswing.geom.IntPoint) : Void;
	function setLocationXY(x : Int, y : Int) : Void;
	function setMaximumHeight(maximumHeight : Int) : Void;
	function setMaximumSize(maximumSize : org.aswing.geom.IntDimension) : Void;
	function setMaximumWidth(maximumWidth : Int) : Void;
	function setMinimumHeight(minimumHeight : Int) : Void;
	function setMinimumSize(minimumSize : org.aswing.geom.IntDimension) : Void;
	function setMinimumWidth(minimumWidth : Int) : Void;
	function setName(name : String) : Void;
	function setOpaque(b : Bool) : Void;
	function setOpaqueSet(b : Bool) : Void;
	function setPreferredHeight(preferredHeight : Int) : Void;
	function setPreferredSize(preferredSize : org.aswing.geom.IntDimension) : Void;
	function setPreferredWidth(preferredWidth : Int) : Void;
	function setSize(newSize : org.aswing.geom.IntDimension) : Void;
	function setSizeWH(w : Int, h : Int) : Void;
	function setToolTipText(t : String) : Void;
	function setUI(newUI : org.aswing.plaf.ComponentUI) : Void;
	function setUIElement(b : Bool) : Void;
	function setVisible(v : Bool) : Void;
	function setWidth(width : Int) : Void;
	function setX(x : Int) : Void;
	function setY(y : Int) : Void;
	function transferFocus() : Bool;
	function transferFocusBackward() : Bool;
	function updateUI() : Void;
	function validate() : Void;
	private var bounds : org.aswing.geom.IntRectangle;
	private var d_visible : Bool;
	private var d_x : Float;
	private var d_y : Float;
	private var drawTransparentTrigger : Bool;
	private var readyToPaint : Bool;
	private var ui : org.aswing.plaf.ComponentUI;
	private var valid : Bool;
	private function clearPreferSizeCaches() : Void;
	private function countMaximumSize() : org.aswing.geom.IntDimension;
	private function countMinimumSize() : org.aswing.geom.IntDimension;
	private function countPreferredSize() : org.aswing.geom.IntDimension;
	private function getFocusTransmit() : Component;
	private function invalidateTree() : Void;
	private function locate() : Void;
	private function paint(b : org.aswing.geom.IntRectangle) : Void;
	private function size() : Void;
}
