package org.aswing;

extern class JFrame extends JWindow {
	function new(?owner : Dynamic, ?title : String, ?modal : Bool) : Void;
	function closeReleased() : Void;
	function getDefaultCloseOperation() : Int;
	function getFrameUI() : org.aswing.plaf.FrameUI;
	function getIcon() : Icon;
	function getMaximizedBounds() : org.aswing.geom.IntRectangle;
	function getResizer() : org.aswing.resizer.Resizer;
	function getState() : Int;
	function getTitle() : String;
	function getTitleBar() : FrameTitleBar;
	function isClosable() : Bool;
	function isDragDirectly() : Bool;
	function isDragDirectlySet() : Bool;
	function isDragable() : Bool;
	function isResizable() : Bool;
	function isResizeDirectly() : Bool;
	function setClosable(b : Bool) : Void;
	function setDefaultCloseOperation(operation : Int) : Void;
	function setDragDirectly(b : Bool) : Void;
	function setDragDirectlySet(b : Bool) : Void;
	function setDragable(b : Bool) : Void;
	function setIcon(ico : Icon) : Void;
	function setMaximizedBounds(b : org.aswing.geom.IntRectangle) : Void;
	function setResizable(b : Bool) : Void;
	function setResizeDirectly(b : Bool) : Void;
	function setResizer(r : org.aswing.resizer.Resizer) : Void;
	function setState(s : Int, ?programmatic : Bool) : Void;
	function setTitle(t : String) : Void;
	function setTitleBar(t : FrameTitleBar) : Void;
	function tryToClose() : Void;
	private var closable : Bool;
	private var defaultCloseOperation : Int;
	private var dragDirectly : Bool;
	private var dragDirectlySet : Bool;
	private var dragable : Bool;
	private var icon : Icon;
	private var lastNormalStateBounds : org.aswing.geom.IntRectangle;
	private var maximizedBounds : org.aswing.geom.IntRectangle;
	private var resizable : Bool;
	private var resizer : org.aswing.resizer.Resizer;
	private var resizerController : org.aswing.resizer.ResizerController;
	private var state : Int;
	private var title : String;
	private var titleBar : FrameTitleBar;
	private function doStateChange() : Void;
	private function fireStateChanged(?programmatic : Bool) : Void;
	private function isMaximized() : Bool;
	private function precessIconified(?programmatic : Bool) : Void;
	private function precessMaximized(?programmatic : Bool) : Void;
	private function precessRestored(?programmatic : Bool) : Void;
	private function setSizeToFixMaxmimized() : Void;
	static var DISPOSE_ON_CLOSE : Int;
	static var DO_NOTHING_ON_CLOSE : Int;
	static var HIDE_ON_CLOSE : Int;
	static var ICONIFIED : Int;
	static var MAXIMIZED : Int;
	static var MAXIMIZED_HORIZ : Int;
	static var MAXIMIZED_VERT : Int;
	static var NORMAL : Int;
	static var PROPERTY_TITLE_BAR : String;
}
