package org.aswing;

extern class JFrameTitleBar extends Container, implements FrameTitleBar, implements org.aswing.plaf.UIResource {
	function new() : Void;
	function addExtraControl(c : Component, position : Int) : Void;
	function getCloseButton() : AbstractButton;
	function getFrame() : JWindow;
	function getIcon() : Icon;
	function getIconifiedButton() : AbstractButton;
	function getLabel() : JLabel;
	function getMaximizeButton() : AbstractButton;
	function getRestoreButton() : AbstractButton;
	function getSelf() : Component;
	function getText() : String;
	function isTitleEnabled() : Bool;
	function removeExtraControl(c : Component) : Component;
	function setCloseButton(b : AbstractButton) : Void;
	function setCloseButtonVisible(b : Bool) : Void;
	function setFrame(f : JWindow) : Void;
	function setIcon(i : Icon) : Void;
	function setIconifiedButton(b : AbstractButton) : Void;
	function setIconifiedButtonVisible(b : Bool) : Void;
	function setMaximizeButton(b : AbstractButton) : Void;
	function setMaximizeButtonVisible(b : Bool) : Void;
	function setRestoreButton(b : AbstractButton) : Void;
	function setRestoreButtonVisible(b : Bool) : Void;
	function setText(t : String) : Void;
	function setTitleEnabled(b : Bool) : Void;
	function updateUIPropertiesFromOwner() : Void;
	private var activeTextColor : ASColor;
	private var buttonPane : Container;
	private var buttonPaneLayout : SoftBoxLayout;
	private var closeButton : AbstractButton;
	private var frame : JFrame;
	private var icon : Icon;
	private var iconifiedButton : AbstractButton;
	private var inactiveTextColor : ASColor;
	private var maximizeButton : AbstractButton;
	private var owner : JWindow;
	private var restoreButton : AbstractButton;
	private var text : String;
	private var titleEnabled : Bool;
	private var titleLabel : JLabel;
	private function createCloseButton() : AbstractButton;
	private function createIconifiedButton() : AbstractButton;
	private function createMaximizeButton() : AbstractButton;
	private function createPureButton() : JButton;
	private function createRestoreButton() : AbstractButton;
	private function getFrameIcon(key : String) : Icon;
	private function getFrameUIColor(key : String) : ASColor;
	private function getFrameUIInt(key : String) : Int;
	private function getTitleBGD(key : String) : GroundDecorator;
}
