package org.aswing;

extern class JList extends Container, implements LayoutManager, implements Viewportable, implements org.aswing.event.ListDataListener {
	function new(?listData : Dynamic, ?cellFactory : ListCellFactory) : Void;
	function addLayoutComponent(comp : Component, constraints : Dynamic) : Void;
	function addSelectionInterval(index0 : Int, index1 : Int, ?programmatic : Bool) : Void;
	function addSelectionListener(listener : Dynamic, ?priority : Int, ?useWeakReference : Bool) : Void;
	function addStateListener(listener : Dynamic, ?priority : Int, ?useWeakReference : Bool) : Void;
	function clearSelection(?programmatic : Bool) : Void;
	function contentsChanged(e : org.aswing.event.ListDataEvent) : Void;
	function ensureIndexIsVisible(index : Int) : Void;
	function getAnchorSelectionIndex() : Int;
	function getAutoDragAndDropType() : Int;
	function getCellByIndex(index : Int) : ListCell;
	function getCellFactory() : ListCellFactory;
	function getExtentSize() : org.aswing.geom.IntDimension;
	function getFirstVisibleIndex() : Int;
	function getHorizontalBlockIncrement() : Int;
	function getHorizontalUnitIncrement() : Int;
	function getItemIndexByCell(cell : ListCell) : Int;
	function getLastVisibleIndex() : Int;
	function getLayoutAlignmentX(target : Container) : Float;
	function getLayoutAlignmentY(target : Container) : Float;
	function getLeadSelectionIndex() : Int;
	function getModel() : ListModel;
	function getPreferredCellWidthWhenNoCount() : Int;
	function getSelectedIndex() : Int;
	function getSelectedIndices() : Array<Dynamic>;
	function getSelectedValue() : Dynamic;
	function getSelectedValues() : Array<Dynamic>;
	function getSelectionBackground() : ASColor;
	function getSelectionForeground() : ASColor;
	function getSelectionMode() : Int;
	function getSelectionModel() : ListSelectionModel;
	function getVerticalBlockIncrement() : Int;
	function getVerticalUnitIncrement() : Int;
	function getViewPosition() : org.aswing.geom.IntPoint;
	function getViewSize() : org.aswing.geom.IntDimension;
	function getViewportPane() : Component;
	function getVisibleCellWidth() : Int;
	function getVisibleRowCount() : Int;
	function intervalAdded(e : org.aswing.event.ListDataEvent) : Void;
	function intervalRemoved(e : org.aswing.event.ListDataEvent) : Void;
	function invalidateLayout(target : Container) : Void;
	function isAutoDnDDropTargetAllown() : Bool;
	function isAutoDnDInitiatorAllown() : Bool;
	function isMutableModel() : Bool;
	function isSelectedIndex(index : Int) : Bool;
	function isSelectionEmpty() : Bool;
	function isTracksWidth() : Bool;
	function layoutContainer(target : Container) : Void;
	function maximumLayoutSize(target : Container) : org.aswing.geom.IntDimension;
	function minimumLayoutSize(target : Container) : org.aswing.geom.IntDimension;
	function preferredLayoutSize(target : Container) : org.aswing.geom.IntDimension;
	function removeLayoutComponent(comp : Component) : Void;
	function removeSelectionInterval(index0 : Int, index1 : Int, ?programmatic : Bool) : Void;
	function removeSelectionListener(listener : Dynamic) : Void;
	function removeStateListener(listener : Dynamic) : Void;
	function scrollRectToVisible(contentRect : org.aswing.geom.IntRectangle, ?programmatic : Bool) : Void;
	function scrollToBottomLeft() : Void;
	function scrollToBottomRight() : Void;
	function scrollToTopLeft() : Void;
	function scrollToTopRight() : Void;
	function selectAll(?programmatic : Bool) : Void;
	function setCellFactory(newFactory : ListCellFactory) : Void;
	function setFirstVisibleIndex(index : Int) : Void;
	function setHorizontalBlockIncrement(increment : Int) : Void;
	function setHorizontalUnitIncrement(increment : Int) : Void;
	function setLastVisibleIndex(index : Int) : Void;
	function setListData(ld : Array<Dynamic>) : Void;
	function setModel(m : ListModel) : Void;
	function setPreferredCellWidthWhenNoCount(preferredWidthWhenNoCount : Int) : Void;
	function setSelectedIndex(index : Int, ?programmatic : Bool) : Void;
	function setSelectedIndices(indices : Array<Dynamic>, ?programmatic : Bool) : Void;
	function setSelectedValue(value : Dynamic, ?programmatic : Bool) : Void;
	function setSelectedValues(values : Array<Dynamic>, ?programmatic : Bool) : Void;
	function setSelectionBackground(selectionBackground : ASColor) : Void;
	function setSelectionForeground(selectionForeground : ASColor) : Void;
	function setSelectionInterval(index0 : Int, index1 : Int, ?programmatic : Bool) : Void;
	function setSelectionMode(sm : Int) : Void;
	function setSelectionModel(m : ListSelectionModel) : Void;
	function setTracksWidth(b : Bool) : Void;
	function setVerticalBlockIncrement(increment : Int) : Void;
	function setVerticalUnitIncrement(increment : Int) : Void;
	function setViewPosition(p : org.aswing.geom.IntPoint, ?programmatic : Bool) : Void;
	function setViewportTestSize(s : org.aswing.geom.IntDimension) : Void;
	function setVisibleCellWidth(w : Int) : Void;
	function setVisibleRowCount(c : Int) : Void;
	function updateListView() : Void;
	private var cellPane : CellPane;
	private function addCellToContainer(cell : ListCell) : Void;
	private function addHandlersToCell(cellCom : Component) : Void;
	private function createItemEventObj(cellCom : Dynamic, type : String, e : flash.events.MouseEvent) : org.aswing.event.ListItemEvent;
	private function fireStateChanged(?programmatic : Bool) : Void;
	private function getItemIndexByCellComponent(item : Component) : Int;
	private function removeCellFromeContainer(cell : ListCell) : Void;
	private function removeHandlersFromCell(cellCom : Component) : Void;
	static var AUTO_INCREMENT : Int;
	static var DND_COPY : Int;
	static var DND_MOVE : Int;
	static var DND_NONE : Int;
	static var MULTIPLE_SELECTION : Int;
	static var SINGLE_SELECTION : Int;
}
