package org.aswing;

extern class JTextComponent extends Component, implements EditableComponent {
	function new() : Void;
	function appendByReplace(newText : String) : Void;
	function appendText(newText : String) : Void;
	function getCSS() : flash.text.StyleSheet;
	function getDefaultTextFormat() : flash.text.TextFormat;
	function getHtmlText() : String;
	function getLength() : Int;
	function getMaxChars() : Int;
	function getRestrict() : String;
	function getSelectionBeginIndex() : Int;
	function getSelectionEndIndex() : Int;
	function getText() : String;
	function getTextField() : flash.text.TextField;
	function getTextFormat(?beginIndex : Int, ?endIndex : Int) : flash.text.TextFormat;
	function isCondenseWhite() : Bool;
	function isDisplayAsPassword() : Bool;
	function isEditable() : Bool;
	function isUseRichTextClipboard() : Bool;
	function isWordWrap() : Bool;
	function replaceSelectedText(value : String) : Void;
	function replaceText(beginIndex : Int, endIndex : Int, newText : String) : Void;
	function selectAll() : Void;
	function setCSS(css : flash.text.StyleSheet) : Void;
	function setCondenseWhite(b : Bool) : Void;
	function setDefaultTextFormat(dtf : flash.text.TextFormat) : Void;
	function setDisplayAsPassword(b : Bool) : Void;
	function setEditable(b : Bool) : Void;
	function setHtmlText(ht : String) : Void;
	function setMaxChars(n : Int) : Void;
	function setRestrict(res : String) : Void;
	function setSelection(beginIndex : Int, endIndex : Int) : Void;
	function setText(text : String) : Void;
	function setTextFormat(tf : flash.text.TextFormat, ?beginIndex : Int, ?endIndex : Int) : Void;
	function setUseRichTextClipboard(b : Bool) : Void;
	function setWordWrap(b : Bool) : Void;
	private var columnRowCounted : Bool;
	private var columnWidth : Int;
	private var heightMargin : Int;
	private var rowHeight : Int;
	private var widthMargin : Int;
	private function applyBoundsToText(b : org.aswing.geom.IntRectangle) : Void;
	private function countColumnRowSize() : Void;
	private function getColumnWidth() : Int;
	private function getHeightMargin() : Int;
	private function getRowHeight() : Int;
	private function getTextFieldAutoSizedSize(?forceWidth : Int, ?forceHeight : Int) : org.aswing.geom.IntDimension;
	private function getWidthMargin() : Int;
	private function invalidateColumnRowSize() : Void;
	private function isAutoSize() : Bool;
}
