package org.aswing;

extern class JTree extends Container, implements Viewportable, implements org.aswing.event.TreeModelListener, implements org.aswing.event.CellEditorListener {
	function new(?newModel : org.aswing.tree.TreeModel) : Void;
	function addSelectionInterval(index0 : Int, index1 : Int, ?programmatic : Bool) : Void;
	function addSelectionListener(listener : Dynamic, ?priority : Int, ?useWeakReference : Bool) : Void;
	function addSelectionPath(path : org.aswing.tree.TreePath, ?programmatic : Bool) : Void;
	function addSelectionPaths(paths : Array<Dynamic>, ?programmatic : Bool) : Void;
	function addSelectionRow(row : Int, ?programmatic : Bool) : Void;
	function addSelectionRows(rows : Array<Dynamic>, ?programmatic : Bool) : Void;
	function addStateListener(listener : Dynamic, ?priority : Int, ?useWeakReference : Bool) : Void;
	function cancelEditing() : Void;
	function clearSelection(?programmatic : Bool) : Void;
	function collapsePath(path : org.aswing.tree.TreePath) : Void;
	function collapseRow(row : Int) : Void;
	function editingCanceled(source : CellEditor) : Void;
	function editingStopped(source : CellEditor) : Void;
	function expandPath(path : org.aswing.tree.TreePath) : Void;
	function expandRow(row : Int) : Void;
	function fireTreeCollapsed(path : org.aswing.tree.TreePath) : Void;
	function fireTreeExpanded(path : org.aswing.tree.TreePath) : Void;
	function fireTreeWillCollapse(path : org.aswing.tree.TreePath) : Void;
	function fireTreeWillExpand(path : org.aswing.tree.TreePath) : Void;
	function getAnchorSelectionPath() : org.aswing.tree.TreePath;
	function getCellEditor() : org.aswing.tree.TreeCellEditor;
	function getCellFactory() : org.aswing.tree.TreeCellFactory;
	function getClosestPathForLocation(x : Int, y : Int) : org.aswing.tree.TreePath;
	function getClosestRowForLocation(x : Int, y : Int) : Int;
	function getEditingPath() : org.aswing.tree.TreePath;
	function getExpandedDescendants(parent : org.aswing.tree.TreePath) : Array<Dynamic>;
	function getExtentSize() : org.aswing.geom.IntDimension;
	function getFixedCellWidth() : Int;
	function getHorizontalBlockIncrement() : Int;
	function getHorizontalUnitIncrement() : Int;
	function getLastSelectedPathComponent() : Dynamic;
	function getLeadSelectionPath() : org.aswing.tree.TreePath;
	function getLeadSelectionRow() : Int;
	function getLogicLocationFromPixelLocation(p : org.aswing.geom.IntPoint) : org.aswing.geom.IntPoint;
	function getMaxSelectionRow() : Int;
	function getMinSelectionRow() : Int;
	function getModel() : org.aswing.tree.TreeModel;
	function getMousePointedPath() : org.aswing.tree.TreePath;
	function getPathBounds(path : org.aswing.tree.TreePath) : org.aswing.geom.IntRectangle;
	function getPathForLocation(x : Int, y : Int) : org.aswing.tree.TreePath;
	function getPathForRow(row : Int) : org.aswing.tree.TreePath;
	function getPixelLocationFromLogicLocation(p : org.aswing.geom.IntPoint) : org.aswing.geom.IntPoint;
	function getRowBounds(row : Int) : org.aswing.geom.IntRectangle;
	function getRowCount() : Int;
	function getRowForLocation(x : Int, y : Int) : Int;
	function getRowForPath(path : org.aswing.tree.TreePath) : Int;
	function getRowHeight() : Int;
	function getSelectionBackground() : ASColor;
	function getSelectionCount() : Int;
	function getSelectionForeground() : ASColor;
	function getSelectionModel() : org.aswing.tree.TreeSelectionModel;
	function getSelectionPath() : org.aswing.tree.TreePath;
	function getSelectionPaths() : Array<Dynamic>;
	function getSelectionRow() : Int;
	function getSelectionRows() : Array<Dynamic>;
	function getToggleClickCount() : Int;
	function getTreeUI() : org.aswing.plaf.TreeUI;
	function getVerticalBlockIncrement() : Int;
	function getVerticalUnitIncrement() : Int;
	function getViewPosition() : org.aswing.geom.IntPoint;
	function getViewSize() : org.aswing.geom.IntDimension;
	function getViewportPane() : Component;
	function getVisibleRect() : org.aswing.geom.IntRectangle;
	function getVisibleRowCount() : Int;
	function hasBeenExpanded(path : org.aswing.tree.TreePath) : Bool;
	function isCollapsed(path : org.aswing.tree.TreePath) : Bool;
	function isCollapsedOfRow(row : Int) : Bool;
	function isEditable() : Bool;
	function isEditing() : Bool;
	function isExpanded(path : org.aswing.tree.TreePath) : Bool;
	function isExpandedOfRow(row : Int) : Bool;
	function isExpandsSelectedPaths() : Bool;
	function isInvokesStopCellEditing() : Bool;
	function isPathEditable(path : org.aswing.tree.TreePath) : Bool;
	function isPathSelected(path : org.aswing.tree.TreePath) : Bool;
	function isPathVisible(path : org.aswing.tree.TreePath) : Bool;
	function isRootVisible() : Bool;
	function isRowHeightSet() : Bool;
	function isRowSelected(row : Int) : Bool;
	function isScrollsOnExpand() : Bool;
	function isScrollsOnExpandSet() : Bool;
	function isSelectionEmpty() : Bool;
	function makePathVisible(path : org.aswing.tree.TreePath) : Void;
	function removeDescendantSelectedPathsWithEvent(e : org.aswing.event.TreeModelEvent) : Void;
	function removeSelectionInterval(index0 : Int, index1 : Int, ?programmatic : Bool) : Void;
	function removeSelectionListener(listener : Dynamic) : Void;
	function removeSelectionPath(path : org.aswing.tree.TreePath, ?programmatic : Bool) : Void;
	function removeSelectionPaths(paths : Array<Dynamic>, ?programmatic : Bool) : Void;
	function removeSelectionRow(row : Int, ?programmatic : Bool) : Void;
	function removeSelectionRows(rows : Array<Dynamic>, ?programmatic : Bool) : Void;
	function removeStateListener(listener : Dynamic) : Void;
	function scrollPathToVisible(path : org.aswing.tree.TreePath) : Void;
	function scrollRectToVisible(contentRect : org.aswing.geom.IntRectangle, ?programmatic : Bool) : Void;
	function scrollRowToVisible(row : Int) : Void;
	function setAnchorSelectionPath(newPath : org.aswing.tree.TreePath) : Void;
	function setCellEditor(cellEditor : org.aswing.tree.TreeCellEditor) : Void;
	function setCellFactory(x : org.aswing.tree.TreeCellFactory) : Void;
	function setEditable(flag : Bool) : Void;
	function setExpandsSelectedPaths(newValue : Bool) : Void;
	function setFixedCellWidth(width : Int) : Void;
	function setHorizontalBlockIncrement(increment : Int) : Void;
	function setHorizontalUnitIncrement(increment : Int) : Void;
	function setInvokesStopCellEditing(newValue : Bool) : Void;
	function setLeadSelectionPath(newPath : org.aswing.tree.TreePath) : Void;
	function setModel(newModel : org.aswing.tree.TreeModel) : Void;
	function setRootVisible(rootVisible : Bool) : Void;
	function setRowHeight(rowHeight : Int) : Void;
	function setRowHeightSet(b : Bool) : Void;
	function setScrollsOnExpand(newValue : Bool) : Void;
	function setScrollsOnExpandSet(b : Bool) : Void;
	function setSelectionBackground(selectionBackground : ASColor) : Void;
	function setSelectionForeground(selectionForeground : ASColor) : Void;
	function setSelectionInterval(index0 : Int, index1 : Int, ?programmatic : Bool) : Void;
	function setSelectionMode(mode : Int) : Void;
	function setSelectionModel(selectionModel : org.aswing.tree.TreeSelectionModel) : Void;
	function setSelectionPath(path : org.aswing.tree.TreePath, ?programmatic : Bool) : Void;
	function setSelectionPaths(paths : Array<Dynamic>, ?programmatic : Bool) : Void;
	function setSelectionRow(row : Int, ?programmatic : Bool) : Void;
	function setSelectionRows(rows : Array<Dynamic>, ?programmatic : Bool) : Void;
	function setToggleClickCount(clickCount : Int) : Void;
	function setVerticalBlockIncrement(increment : Int) : Void;
	function setVerticalUnitIncrement(increment : Int) : Void;
	function setViewPosition(p : org.aswing.geom.IntPoint, ?programmatic : Bool) : Void;
	function setViewportTestSize(s : org.aswing.geom.IntDimension) : Void;
	function setVisibleRowCount(newCount : Int) : Void;
	function startEditingAtPath(path : org.aswing.tree.TreePath) : Void;
	function stopEditing() : Bool;
	function treeDidChange() : Void;
	function treeNodesChanged(e : org.aswing.event.TreeModelEvent) : Void;
	function treeNodesInserted(e : org.aswing.event.TreeModelEvent) : Void;
	function treeNodesRemoved(e : org.aswing.event.TreeModelEvent) : Void;
	function treeStructureChanged(e : org.aswing.event.TreeModelEvent) : Void;
	private function expandRoot() : Void;
	private function firePropertyChange(pn : String, oldValue : Dynamic, newValue : Dynamic) : Void;
	private function fireStateChanged(?programmatic : Bool) : Void;
	private function getModelIndexsForPath(path : org.aswing.tree.TreePath) : Array<Dynamic>;
	private function getPathForIndexs(indexs : Array<Dynamic>) : org.aswing.tree.TreePath;
	private function setExpandedState(path : org.aswing.tree.TreePath, state : Bool) : Void;
	static var ANCHOR_SELECTION_PATH_PROPERTY : String;
	static var AUTO_INCREMENT : Int;
	static var CELL_EDITOR_PROPERTY : String;
	static var CELL_FACTORY_PROPERTY : String;
	static var CONTIGUOUS_TREE_SELECTION : Int;
	static var DISCONTIGUOUS_TREE_SELECTION : Int;
	static var EDITABLE_PROPERTY : String;
	static var EXPANDS_SELECTED_PATHS_PROPERTY : String;
	static var FONT_PROPERTY : String;
	static var INVOKES_STOP_CELL_EDITING_PROPERTY : String;
	static var LEAD_SELECTION_PATH_PROPERTY : String;
	static var ROOT_VISIBLE_PROPERTY : String;
	static var ROW_HEIGHT_PROPERTY : String;
	static var SCROLLS_ON_EXPAND_PROPERTY : String;
	static var SELECTION_MODEL_PROPERTY : String;
	static var SINGLE_TREE_SELECTION : Int;
	static var TOGGLE_CLICK_COUNT_PROPERTY : String;
	static var TREE_MODEL_PROPERTY : String;
	static var VISIBLE_ROW_COUNT_PROPERTY : String;
}
