package org.aswing.plaf.basic;

extern class BasicTabbedPaneUI extends org.aswing.plaf.BaseComponentUI, implements org.aswing.LayoutManager {
	function new() : Void;
	function addLayoutComponent(comp : org.aswing.Component, constraints : Dynamic) : Void;
	function getLayoutAlignmentX(target : org.aswing.Container) : Float;
	function getLayoutAlignmentY(target : org.aswing.Container) : Float;
	function invalidateLayout(target : org.aswing.Container) : Void;
	function layoutContainer(target : org.aswing.Container) : Void;
	function maximumLayoutSize(target : org.aswing.Container) : org.aswing.geom.IntDimension;
	function minimumLayoutSize(target : org.aswing.Container) : org.aswing.geom.IntDimension;
	function preferredLayoutSize(target : org.aswing.Container) : org.aswing.geom.IntDimension;
	function removeLayoutComponent(comp : org.aswing.Component) : Void;
	private var arrowLightColor : org.aswing.ASColor;
	private var arrowShadowColor : org.aswing.ASColor;
	private var buttonHolderMC : flash.display.Sprite;
	private var buttonMCPane : org.aswing.Container;
	private var contentMargin : org.aswing.Insets;
	private var contentRoundLineThickness : Int;
	private var darkShadow : org.aswing.ASColor;
	private var drawnTabBoundArray : Array<Dynamic>;
	private var firstIndex : Int;
	private var highlight : org.aswing.ASColor;
	private var lastIndex : Int;
	private var lightHighlight : org.aswing.ASColor;
	private var maxTabSize : org.aswing.geom.IntDimension;
	private var maxTabWidth : Int;
	private var minimumSize : org.aswing.geom.IntDimension;
	private var nextButton : org.aswing.AbstractButton;
	private var prefferedSize : org.aswing.geom.IntDimension;
	private var prevButton : org.aswing.AbstractButton;
	private var selectedTabExpandInsets : org.aswing.Insets;
	private var shadow : org.aswing.ASColor;
	private var tabBarMC : flash.display.Sprite;
	private var tabBarMaskMC : flash.display.Shape;
	private var tabBarSize : org.aswing.geom.IntDimension;
	private var tabBorderInsets : org.aswing.Insets;
	private var tabBoundArray : Array<Dynamic>;
	private var tabGap : Int;
	private var tabbedPane : org.aswing.JTabbedPane;
	private var tabs : Array<Dynamic>;
	private var topBlankSpace : Int;
	private var uiRootMC : flash.display.Sprite;
	private var windowBG : org.aswing.ASColor;
	private function __nextButtonReleased(e : flash.events.Event) : Void;
	private function __onNavKeyDown(e : org.aswing.event.FocusKeyEvent) : Void;
	private function __onSelectionChanged(e : org.aswing.event.InteractiveEvent) : Void;
	private function __onTabPanePressed(e : flash.events.Event) : Void;
	private function __prevButtonReleased(e : flash.events.Event) : Void;
	private function countPreferredTabSizeAt(index : Int) : org.aswing.geom.IntDimension;
	private function createArrowIcon(direction : Float, enable : Bool) : org.aswing.Icon;
	private function createNewTab() : org.aswing.plaf.basic.tabbedpane.Tab;
	private function createNextButton() : org.aswing.AbstractButton;
	private function createPrevButton() : org.aswing.AbstractButton;
	private function createTabBarGraphics() : org.aswing.graphics.Graphics2D;
	private function createUIAssets() : Void;
	private function drawBaseLine(tabBarBounds : org.aswing.geom.IntRectangle, g : org.aswing.graphics.Graphics2D, fullB : org.aswing.geom.IntRectangle) : Void;
	private function drawTabAt(index : Int, bounds : org.aswing.geom.IntRectangle, paneBounds : org.aswing.geom.IntRectangle, g : org.aswing.graphics.Graphics2D, transformedTabMargin : org.aswing.Insets) : Void;
	private function drawTabBorderAt(index : Int, b : org.aswing.geom.IntRectangle, paneBounds : org.aswing.geom.IntRectangle, g : org.aswing.graphics.Graphics2D) : Void;
	private function drawTabWithFullInfosAt(index : Int, paneBounds : org.aswing.geom.IntRectangle, bounds : org.aswing.geom.IntRectangle, g : org.aswing.graphics.Graphics2D, tabBarBounds : org.aswing.geom.IntRectangle, offsetPoint : org.aswing.geom.IntPoint, transformedTabMargin : org.aswing.Insets) : Int;
	private function getDrawnTabBounds(index : Int) : org.aswing.geom.IntRectangle;
	private function getMousedOnTabIndex() : Int;
	private function getPropertyPrefix() : String;
	private function getSelectedTab() : org.aswing.plaf.basic.tabbedpane.Tab;
	private function getTab(i : Int) : org.aswing.plaf.basic.tabbedpane.Tab;
	private function getTabBarSize() : org.aswing.geom.IntDimension;
	private function getTabBorderInsets() : org.aswing.Insets;
	private function getTabBoundArray() : Array<Dynamic>;
	private function getTabColor(index : Int) : org.aswing.ASColor;
	private function getTransformedMargin() : org.aswing.Insets;
	private function indexOfTabComponent(tab : org.aswing.Component) : Int;
	private function installComponents() : Void;
	private function installDefaults() : Void;
	private function installListeners() : Void;
	private function isTabHorizontalPlacing() : Bool;
	private function removeUIAssets() : Void;
	private function setDrawnTabBounds(index : Int, b : org.aswing.geom.IntRectangle, paneBounds : org.aswing.geom.IntRectangle) : Void;
	private function setTabMarginProperty(tab : org.aswing.plaf.basic.tabbedpane.Tab, margin : org.aswing.Insets) : Void;
	private function setTabProperties(header : org.aswing.plaf.basic.tabbedpane.Tab, i : Int) : Void;
	private function setTraversingTrue() : Void;
	private function synTabProperties() : Void;
	private function synTabs() : Void;
	private function uninstallComponents() : Void;
	private function uninstallDefaults() : Void;
	private function uninstallListeners() : Void;
}
