package org.aswing.plaf.basic;

extern class BasicTreeUI extends org.aswing.plaf.BaseComponentUI, implements org.aswing.plaf.TreeUI, implements org.aswing.tree.NodeDimensions, implements org.aswing.event.TreeModelListener {
	function new() : Void;
	function __treeCollapsed(e : org.aswing.event.TreeEvent) : Void;
	function __treeExpanded(e : org.aswing.event.TreeEvent) : Void;
	function cancelEditing(tree : org.aswing.JTree) : Void;
	function countNodeDimensions(value : Dynamic, row : Int, depth : Int, expanded : Bool, size : org.aswing.geom.IntRectangle) : org.aswing.geom.IntRectangle;
	function getClosestPathForLocation(tree : org.aswing.JTree, x : Int, y : Int) : org.aswing.tree.TreePath;
	function getEditingPath(tree : org.aswing.JTree) : org.aswing.tree.TreePath;
	function getLeftChildIndent() : Int;
	function getMousePointedPath() : org.aswing.tree.TreePath;
	function getPathBounds(tree : org.aswing.JTree, path : org.aswing.tree.TreePath) : org.aswing.geom.IntRectangle;
	function getPathForRow(tree : org.aswing.JTree, row : Int) : org.aswing.tree.TreePath;
	function getRightChildIndent() : Int;
	function getRowCount(tree : org.aswing.JTree) : Int;
	function getRowForPath(tree : org.aswing.JTree, path : org.aswing.tree.TreePath) : Int;
	function getViewSize(theTree : org.aswing.JTree) : org.aswing.geom.IntDimension;
	function isEditing(tree : org.aswing.JTree) : Bool;
	function setLeftChildIndent(newAmount : Int) : Void;
	function setRightChildIndent(newAmount : Int) : Void;
	function startEditingAtPath(tree : org.aswing.JTree, path : org.aswing.tree.TreePath) : Bool;
	function stopEditing(tree : org.aswing.JTree) : Bool;
	function toString() : String;
	function treeNodesChanged(e : org.aswing.event.TreeModelEvent) : Void;
	function treeNodesInserted(e : org.aswing.event.TreeModelEvent) : Void;
	function treeNodesRemoved(e : org.aswing.event.TreeModelEvent) : Void;
	function treeStructureChanged(e : org.aswing.event.TreeModelEvent) : Void;
	private var cells : org.aswing.util.ArrayList;
	private var currentCellRenderer : org.aswing.tree.TreeCell;
	private var depthOffset : Int;
	private var editingPath : org.aswing.tree.TreePath;
	private var editor : org.aswing.tree.TreeCellEditor;
	private var expandControl : org.aswing.plaf.basic.tree.ExpandControl;
	private var ignoreLAChange : Bool;
	private var lastViewPosition : org.aswing.geom.IntPoint;
	private var leftChildIndent : Int;
	private var rendererPane : org.aswing.CellPane;
	private var rightChildIndent : Int;
	private var selectionModel : org.aswing.tree.TreeSelectionModel;
	private var totalChildIndent : Int;
	private var tree : org.aswing.JTree;
	private var treeModel : org.aswing.tree.TreeModel;
	private var treeState : org.aswing.tree.AbstractLayoutCache;
	private var validCachedViewSize : Bool;
	private var viewSize : org.aswing.geom.IntDimension;
	private function cellFactoryChanged() : Void;
	private function checkCreateCells() : Void;
	private function createRendererPaneGraphics() : org.aswing.graphics.Graphics2D;
	private function doSelectPathForEvent(e : flash.events.MouseEvent) : Void;
	private function ensureRowsAreVisible(beginRow : Int, endRow : Int) : Void;
	private function getEditionKey() : UInt;
	private function getPropertyPrefix() : String;
	private function getRowX(row : Int, depth : Int) : Int;
	private function handleExpandControlClick(path : org.aswing.tree.TreePath, mouseX : Int, mouseY : Int) : Void;
	private function installComponents() : Void;
	private function installDefaults() : Void;
	private function installListeners() : Void;
	private function isControlKey(code : UInt) : Bool;
	private function isLocationInExpandControl(path : org.aswing.tree.TreePath, mouseX : Int, mouseY : Int) : Bool;
	private function paintExpandControl(g : org.aswing.graphics.Graphics2D, bounds : org.aswing.geom.IntRectangle, path : org.aswing.tree.TreePath, row : Int, expanded : Bool, leaf : Bool) : Void;
	private function positRendererPaneX(viewX : Int) : Void;
	private function repaintPath(path : org.aswing.tree.TreePath) : Void;
	private function selectPathForEvent(path : org.aswing.tree.TreePath, e : flash.events.MouseEvent) : Void;
	private function setCellEditor(editor : org.aswing.tree.TreeCellEditor) : Void;
	private function setEditable(newValue : Bool) : Void;
	private function setModel(tm : org.aswing.tree.TreeModel) : Void;
	private function setRootVisible(newValue : Bool) : Void;
	private function setRowHeight(rowHeight : Int) : Void;
	private function setSelectionModel(sm : org.aswing.tree.TreeSelectionModel) : Void;
	private function toggleExpandState(path : org.aswing.tree.TreePath) : Void;
	private function uninstallComponents() : Void;
	private function uninstallDefaults() : Void;
	private function uninstallListeners() : Void;
	private function updateCachedViewSize() : Void;
	private function updateDepthOffset() : Void;
	private function updateExpandedDescendants(path : org.aswing.tree.TreePath) : Void;
	private function updateLayoutCacheExpandedNodes() : Void;
	private function updateLeadRow() : Void;
	private function updateSize() : Void;
}
