package org.aswing.plaf.basic;

extern class BasicMenuItemUI extends org.aswing.plaf.BaseComponentUI, implements org.aswing.plaf.MenuElementUI {
	function new() : Void;
	function getPath() : Array<Dynamic>;
	function processKeyEvent(code : UInt) : Void;
	private var accelTextField : flash.text.TextField;
	private var acceleratorFont : org.aswing.ASFont;
	private var acceleratorFontValidated : Bool;
	private var acceleratorForeground : org.aswing.ASColor;
	private var acceleratorSelectionForeground : org.aswing.ASColor;
	private var arrowIcon : org.aswing.Icon;
	private var checkIcon : org.aswing.Icon;
	private var defaultTextIconGap : Int;
	private var disabledForeground : org.aswing.ASColor;
	private var menuItem : org.aswing.JMenuItem;
	private var menuItemLis : Dynamic;
	private var selectionBackground : org.aswing.ASColor;
	private var selectionForeground : org.aswing.ASColor;
	private var textField : flash.text.TextField;
	private function __menuItemAct(e : org.aswing.event.AWEvent) : Void;
	private function __menuItemRollOut(e : flash.events.MouseEvent) : Void;
	private function __menuItemRollOver(e : flash.events.MouseEvent) : Void;
	private function __menuStateChanged(e : flash.events.Event) : Void;
	private function getAcceleratorText(b : org.aswing.JMenuItem) : String;
	private function getIcons() : Array<Dynamic>;
	private function getPreferredMenuItemSize(b : org.aswing.JMenuItem, checkIcon : org.aswing.Icon, arrowIcon : org.aswing.Icon, defaultTextIconGap : Int) : org.aswing.geom.IntDimension;
	private function getPropertyPrefix() : String;
	private function installComponents() : Void;
	private function installDefaults() : Void;
	private function installIcon(icon : org.aswing.Icon) : Void;
	private function installListeners() : Void;
	private function isMenu() : Bool;
	private function isTopMenu() : Bool;
	private function layoutMenuItem(font : org.aswing.ASFont, text : String, accelFont : org.aswing.ASFont, acceleratorText : String, icon : org.aswing.Icon, checkIcon : org.aswing.Icon, arrowIcon : org.aswing.Icon, verticalAlignment : Int, horizontalAlignment : Int, verticalTextPosition : Int, horizontalTextPosition : Int, viewRect : org.aswing.geom.IntRectangle, iconRect : org.aswing.geom.IntRectangle, textRect : org.aswing.geom.IntRectangle, acceleratorRect : org.aswing.geom.IntRectangle, checkIconRect : org.aswing.geom.IntRectangle, arrowIconRect : org.aswing.geom.IntRectangle, textIconGap : Int, menuItemGap : Int) : String;
	private function paintArrowIcon(b : org.aswing.JMenuItem, isPaint : Bool, g : org.aswing.graphics.Graphics2D, x : Int, y : Int) : Void;
	private function paintCheckIcon(b : org.aswing.JMenuItem, isPaint : Bool, g : org.aswing.graphics.Graphics2D, x : Int, y : Int) : Void;
	private function paintIcon(b : org.aswing.JMenuItem, icon : org.aswing.Icon, g : org.aswing.graphics.Graphics2D, x : Int, y : Int) : Void;
	private function paintMenuBackground(menuItem : org.aswing.JMenuItem, g : org.aswing.graphics.Graphics2D, r : org.aswing.geom.IntRectangle, bgColor : org.aswing.ASColor) : Void;
	private function paintMenuItem(b : org.aswing.JMenuItem, g : org.aswing.graphics.Graphics2D, r : org.aswing.geom.IntRectangle, checkIcon : org.aswing.Icon, arrowIcon : org.aswing.Icon, background : org.aswing.ASColor, foreground : org.aswing.ASColor, defaultTextIconGap : Int) : Void;
	private function paintTextField(b : org.aswing.JMenuItem, tRect : org.aswing.geom.IntRectangle, textField : flash.text.TextField, text : String, font : org.aswing.ASFont, color : org.aswing.ASColor, validateFont : Bool) : Void;
	private function resetRects() : Void;
	private function setIconVisible(icon : org.aswing.Icon, visible : Bool) : Void;
	private function shouldPaintSelected() : Bool;
	private function uninstallComponents() : Void;
	private function uninstallDefaults() : Void;
	private function uninstallIcon(icon : org.aswing.Icon) : Void;
	private function uninstallListeners() : Void;
	private function useCheckAndArrow() : Bool;
	static var MAX_ACC_WIDTH : String;
	static var MAX_TEXT_WIDTH : String;
}
