package org.aswing.plaf.basic;

extern class BasicSplitPaneUI extends org.aswing.plaf.SplitPaneUI, implements org.aswing.LayoutManager {
	function new() : Void;
	function addLayoutComponent(comp : org.aswing.Component, constraints : Dynamic) : Void;
	function getLayoutAlignmentX(target : org.aswing.Container) : Float;
	function getLayoutAlignmentY(target : org.aswing.Container) : Float;
	function getMaximumDividerLocation() : Int;
	function getMinimumDividerLocation() : Int;
	function invalidateLayout(target : org.aswing.Container) : Void;
	function layoutContainer(target : org.aswing.Container) : Void;
	function layoutWithLocation(location : Int) : Void;
	function maximumLayoutSize(target : org.aswing.Container) : org.aswing.geom.IntDimension;
	function minimumLayoutSize(target : org.aswing.Container) : org.aswing.geom.IntDimension;
	function preferredLayoutSize(target : org.aswing.Container) : org.aswing.geom.IntDimension;
	function removeLayoutComponent(comp : org.aswing.Component) : Void;
	private var cursorManager : org.aswing.CursorManager;
	private var defaultDividerSize : Int;
	private var divider : org.aswing.plaf.basic.splitpane.Divider;
	private var dragRepresentationMC : flash.display.Shape;
	private var hSplitCursor : flash.display.DisplayObject;
	private var lastContentSize : org.aswing.geom.IntDimension;
	private var mouseInDividerFlag : Bool;
	private var mouseLis : Dynamic;
	private var presentDragColor : org.aswing.ASColor;
	private var pressFlag : Bool;
	private var sp : org.aswing.JSplitPane;
	private var spLis : Dynamic;
	private var spliting : Bool;
	private var startDividerPos : org.aswing.geom.IntPoint;
	private var startDragPos : org.aswing.geom.IntPoint;
	private var startLocation : Int;
	private var vSplitCursor : flash.display.DisplayObject;
	private function __collapseLeft(e : org.aswing.event.AWEvent) : Void;
	private function __collapseRight(e : org.aswing.event.AWEvent) : Void;
	private function __div_location_changed(e : org.aswing.event.InteractiveEvent) : Void;
	private function __div_mouse_moving(e : flash.events.MouseEvent) : Void;
	private function __div_pressed(e : flash.events.MouseEvent) : Void;
	private function __div_released(e : org.aswing.event.ReleaseEvent) : Void;
	private function __div_rollout(e : flash.events.Event) : Void;
	private function __div_rollover(e : flash.events.MouseEvent) : Void;
	private function __on_splitpane_key_down(e : org.aswing.event.FocusKeyEvent) : Void;
	private function createDivider() : org.aswing.plaf.basic.splitpane.Divider;
	private function createSplitCursor(vertical : Bool) : flash.display.DisplayObject;
	private function getCurrentMovedDistance() : Int;
	private function getDefaultDividerSize() : Int;
	private function getDividerSize() : Int;
	private function getPropertyPrefix() : String;
	private function hideMoveCursor() : Void;
	private function installComponents() : Void;
	private function installDefaults() : Void;
	private function installListeners() : Void;
	private function isVertical() : Bool;
	private function paintDividerDragingRepresention(g : org.aswing.graphics.Graphics2D) : Void;
	private function restrictDividerLocation(loc : Int) : Int;
	private function showMoveCursor() : Void;
	private function uninstallComponents() : Void;
	private function uninstallDefaults() : Void;
	private function uninstallListeners() : Void;
	private function validateDivMoveWithCurrentMousePos() : Void;
}
